### ISSUE TITLE
how to set the threshold?

### ISSUE THREAD

**Issue by hensonwells** [rafat/wavelib#22]
Hello,thanks for your lib.
I wanna try to use the dwt to denoise for the 1D signals, don't know how to set the threshold for the coeffs[i],
I follow the DWT Example Code,the I got result like figure 1，what I expect is like  figure 2 which was running in pywt.
Could u help me with that?
Thanks a lot~

![wave-1d](https://user-images.githubusercontent.com/22005661/89499336-697bcd00-d7f2-11ea-8da7-c8a3710300bc.png)
![db5](https://user-images.githubusercontent.com/22005661/89499405-8b754f80-d7f2-11ea-89f5-d6ac314c262f.png)

**Comment by rafat** [comment]
I have implemented multiple denoising algorithms at https://github.com/rafat/wdenoise . Generally speaking, you do noise estimation of the signal,take Wavelet Transform, set a threshold for each level of decomposition, attenuate the signal based on the threshold and then take the inverse transform. Check the different thresholding algorithms here https://github.com/rafat/wdenoise/blob/master/src/wdenoise.c

You can also upload your signal here -> http://rafat.github.io/wavelib/#/ and denoise it directly .

**Comment by hensonwells** [comment]
> I have implemented multiple denoising algorithms at https://github.com/rafat/wdenoise . Generally speaking, you do noise estimation of the signal,take Wavelet Transform, set a threshold for each level of decomposition, attenuate the signal based on the threshold and then take the inverse transform. Check the different thresholding algorithms here https://github.com/rafat/wdenoise/blob/master/src/wdenoise.c
> 
> You can also upload your signal here -> http://rafat.github.io/wavelib/#/ and denoise it directly .

It helped a lot.
Thanks  again : )
