### ISSUE TITLE
Support analyzing sound from mp3 files?

### ISSUE THREAD

**Issue by wave-glsl** [rafat/wavelib#24]
I've tried uploading some, but the demo app seems to misinterpret them somehow: it shows a flat waveform with a couple peaks.

As far as coding is concerned, extracting the waveform in the PCM format can be done with [AudioContext.decodeAudioData](https://webaudio.github.io/web-audio-api/#dom-baseaudiocontext-decodeaudiodata).

From reading sources, I see you are using `reader.readAsText(finp1)` with some text format. Here are some code snippets to allow uploading and decoding audio files:

```html
<input type="file" accept="audio/mpeg" ...>
```

The `accept` attr isn't strictly necessary.

```js
var audioData = await reader.readAsArrayBuffer(finp1);
var audioCtx = new AudioContext({ sampleRate: 44100 });
var pcmBuffer = await audioCtx.decodeAudioData(audioData);
var pcmSamples = new Float32Array(pcmBuffer); // Or Uint8Array?
```

Then you can copy this 100 MB buffer to the wasm memory, etc.

The WebAudio docs say that the output is "often in the form of Float32Array objects." This is a complete disaster. I'd try Uint8Array if Float32Array doesn't work.

**Comment by rafat** [comment]
It works with raw data so you'll have to extract the waveform before
taking its CWT and getting the correct sampling frequency. Set dt to
1.0 /sampling frequency and s0=dt.

On 8/14/20, wave-glsl <notifications@github.com> wrote:
> I've tried uploading some, but the demo app seems to misinterpret them
> somehow: it shows a flat waveform with a couple peaks.
>
> As far as coding is concerned, extracting the waveform in the PCM format can
> be done with `AudioContext.decodeAudioData`.
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/rafat/wavelib/issues/24


-- 
http://rafat.github.io/

**Comment by wave-glsl** [comment]
Where do you host sources for this file `rafat.github.io/wavelib/js/ngfile.js`? I haven't been able to find it on github.

**Comment by rafat** [comment]
Switch to gh-pages branch.

**Comment by wave-glsl** [comment]
Oh, I see. That's a clever trick.

I think your suggestion to convert the mp3 file to a raw text file with float32s won't really work: a typical 10 min audio file at 44 kHz produces 600 x 44e3 = 26 million samples. If we write down each sample in the text format with 10 digits, we'll get a 260 MB text file.

I'm up to write the audio parser. My code above only needs a small correction:

```js
if (finp1.type == "audio/mpeg")
  reader.readAsArrayBuffer(finp1);
else
  reader.readAsText(finp1);
```

```js
reader.onload = async function (e) {
  if (reader.result instanceof ArrayBuffer)
    await parseAudioData(reader.result);
  else
    ... // read the text data as usual
```

The `parseAudioData` code:

```js
async function parseAudioData(inputBuffer) {
  var audioCtx = new AudioContext({ sampleRate: 44100 });
  var pcmData = await audioCtx.decodeAudioData(inputBuffer);
  var pcmSamples = pcmData.getChannelData(0); // Float32Array
  
  wave.sigData = new Float64Array(pcmSamples);
  wave.sigLength = pcmSamples.length;
}
```

This code needs a few millseconds to parse a 10 min mp3 file.

**Comment by wave-glsl** [comment]
Here's a PR: https://github.com/rafat/wavelib/pull/25
