### ISSUE TITLE
float type

### ISSUE THREAD

**Issue by mipac** [rafat/wavelib#30]
hi,
is it possible to dwt a float signal without convert it to double?

**Comment by rafat** [comment]
Hi,

You can cast a float to double but I haven't implemented the single
precision floating point in this library.

Rafat

**Comment by mipac** [comment]
ok, thank you for the reply
do you think that single precision can be problematic?

**Comment by rafat** [comment]
No, there are some precision and rounding off issues as you are
multiplying at multiple levels but that's not an issue for many
embedded systems. I know people have implemented it in single
precision for multicontrollers. If you are only looking to implement
DWT then I have a simple implementation at
https://github.com/rafat/wavemin that can be easily converted to float
from double. Converting the  entire library will be more time
consuming.

**Comment by mipac** [comment]
thanks for the pointer
in fact I'm looking for a simple way to use scattering transform float signal, with fast enough speed
I'll look at the code, but without experience in wavelet transform, i'm not sure to do the job
thank you for your replies
