### ISSUE TITLE
Compilation warnings

### ISSUE THREAD

**Issue by dizcza** [rafat/wavelib#37]
Thanks for the lib, I appreciate the clean C style. I'm using it in ESP-32 to smooth out the raw sensor output of a pressure transducer that records artillery shots at a distance. I picked the "db2" wavelet because it resembles muzzle blast waveforms.

Compilation throws some warnings:

* `M` is set but not used:
https://github.com/rafat/wavelib/blob/a92456d2e20451772dd76c2a0a3368537ee94184/src/wavelib.c#L3002

* `temp_len` is set but not used:
https://github.com/rafat/wavelib/blob/a92456d2e20451772dd76c2a0a3368537ee94184/src/wavelib.c#L3065-L3070

* `N` is set but not used:
https://github.com/rafat/wavelib/blob/a92456d2e20451772dd76c2a0a3368537ee94184/src/wavelib.c#L3946

I wonder if they can be safely removed?

There are also some "variable may be used uninitialized" warnings treated as errors, for instance, `N` and `s0` in the `cdelta()` function: the if-statements are set not according to the algorithm name but rather according to some math logic. Some compilers set them to 0 on declaration, some do not. There are not many, 5 warnings in total. It'd be nice to have them fixed. I set them to 0 just to avoid compilation errors (I don't want to disable the `-Werror=maybe-uninitialized` flag).

---

Off-topic, I wonder if the output of SWT transform level 1, 128 points of float 32, can be (lossy) compressed / zipped to which compression factor, leveraging the fact they are approximate coefficients of a wavelet transform...

**Comment by rafat** [comment]
I have made the changes and it should've taken care of the warnings. Let me
know if you are still getting any warnings or if anything broke in the
code. As for the compression factor, you can do trial and error to see how
much loss is acceptable for your application.

**Comment by dizcza** [comment]
Here is the full list of compilation warnings and my silly fixes:

```diff
--- a/lib/wavelib/cwt.c
+++ b/lib/wavelib/cwt.c
@@ -126,7 +126,7 @@ void cwavelet(const double *y, int N, double dt, int mother, double param, doubl
 {
 
     int i, j, k, iter;
-    double ymean, freq1, pi, period1, coi1;
+    double ymean, freq1, pi, period1 = 0, coi1 = 0;
     double tmp1, tmp2;
     double scale1;
     double *kwave;
@@ -312,6 +312,11 @@ double cdelta(int mother, double param, double psi0 )
 
     subscale = 8.0;
     dt = 0.25;
+    
+    // set to some value for compiler
+    N = 16;
+    s0 = dt / 4;
+    
     if (mother == 0) {
         N = 16;
         s0 = dt/4;
diff --git a/lib/wavelib/hsfft.c b/lib/wavelib/hsfft.c
index 1d03b60..d04cd10 100644
--- a/lib/wavelib/hsfft.c
+++ b/lib/wavelib/hsfft.c
@@ -60,6 +60,7 @@ static void mixed_radix_dit_rec(fft_data *op,fft_data *ip,const fft_object obj,
 {
 
     int radix,m,ll;
+    radix = obj->factors[inc];  // set to some value for compiler
     if (N > 1) {
         radix = obj->factors[inc];
         //printf("%d \n",radix);
diff --git a/lib/wavelib/wavelib.c b/lib/wavelib/wavelib.c
index 9572c92..c83e5f9 100644
--- a/lib/wavelib/wavelib.c
+++ b/lib/wavelib/wavelib.c
@@ -278,8 +278,8 @@ wpt_object wpt_init(wave_object wave, int siglength, int J)
 cwt_object cwt_init(const char* wave, double param,int siglength, double dt, int J)
 {
     cwt_object obj = NULL;
-    int N, i,nj2,ibase2,mother;
-    double s0, dj;
+    int N, i,nj2,ibase2,mother = 0;
+    double s0 = 0.0, dj = 0.0;
     double t1;
     int m, odd;
     const char *pdefault = "pow";
@@ -2761,6 +2761,7 @@ static void modwt_fft(wt_object wt, const double *inp)
 
     temp_len = wt->siglength;
     len_avg = wt->wave->lpd_len;
+    N = temp_len;
     if (!strcmp(wt->ext, "sym")) {
         N = 2 * temp_len;
     }
@@ -2973,7 +2974,7 @@ static void getMODWTRecCoeff(fft_object fft_fd, fft_object fft_bd, fft_data* app
 double* getMODWTmra(wt_object wt, double *wavecoeffs)
 {
     double *mra;
-    int i, J, temp_len, iter, M, N, len_avg,lmra;
+    int i, J, temp_len, iter, N, len_avg,lmra;
     int lenacc;
     double s;
     fft_data  *cA, *cD, *low_pass, *high_pass, *sig,*ninp;
@@ -2983,6 +2984,7 @@ double* getMODWTmra(wt_object wt, double *wavecoeffs)
 
     N = wt->modwtsiglength;
     len_avg = wt->wave->lpd_len;
+    temp_len = N;
     if (!strcmp(wt->ext, "sym")) {
         temp_len = N / 2;
     }
```

**Comment by rafat** [comment]
Create a pull request

**Comment by rafat** [comment]
There is one issue. 

radix = 0 should be initialized before radix is condtionally set in lines 59-62

**Comment by dizcza** [comment]
True! Good spot.

**Comment by dizcza** [comment]
Fixed
